services:
  # Ollama AI Service only
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - zenodo-network
    restart: unless-stopped

volumes:
  ollama_data:
    driver: local

networks:
  zenodo-network:
    driver: bridge 