version: '3.8'

services:
  # Streamlit Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - /app/venv  # Exclude virtual environment
      - /app/__pycache__  # Exclude cache
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
    depends_on:
      - ollama
    networks:
      - zenodo-network

  # Ollama AI Service
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - zenodo-network
    restart: unless-stopped

  # Future FastAPI Backend (commented out for now)
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.backend
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./src:/app/src
  #   environment:
  #     - ENVIRONMENT=development
  #   depends_on:
  #     - ollama
  #   networks:
  #     - zenodo-network

volumes:
  ollama_data:
    driver: local

networks:
  zenodo-network:
    driver: bridge 